#!/usr/bin/env python3

import fnmatch

import cli
import codeowner_parser


def _get_owners(co_data, path):
    """Get the owner of the file or folder."""
    for _, _, pattern, owners in co_data:
        if fnmatch.filter([path], pattern):
            return owners

    return None


def _main():
    cli_args = cli.parse_args()
    co_data = codeowner_parser.parse_codeowners()
    co_data = sorted(co_data, key=lambda x: x[0])
    co_data.reverse()

    if cli_args.get:
        owners = _get_owners(co_data, cli_args.path)
        if owners:
            print(" ".join(owners))
        else:
            print("No owners found")
        return

    for count, line, pattern, owners in co_data:
        print(f"{count}: {line} {pattern} {owners}")


if __name__ == "__main__":
    _main()
